ARG VER=1.0.0.dev
FROM jupyterhub/singleuser:$VER

USER root

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-utils && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends fonts-dejavu gfortran build-essential libpq-dev unixodbc-dev odbc-postgresql && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip s3contents dask toolz nose s3fs gcsfs dj-database-url psycopg2-binary ipython-sql

RUN conda config --system --prepend channels conda-forge && \
    conda config --system --set auto_update_conda false && \
    conda config --system --set show_channel_urls true

RUN conda install --quiet --yes jupyter notebook jupyterlab && \
    conda clean -tipsy && \
    jupyter labextension install @jupyterlab/hub-extension && \
    npm cache clean --force

# R packages
RUN conda install --quiet --yes \
    'r-base=3.4.1' \
    'r-irkernel=0.8*' \
    'r-plyr=1.8*' \
    'r-devtools=1.13*' \
    'r-tidyverse=1.1*' \
    'r-shiny=1.0*' \
    'r-rmarkdown=1.8*' \
    'r-forecast=8.2*' \
    'r-rsqlite=2.0*' \
    'r-reshape2=1.4*' \
    'r-nycflights13=0.2*' \
    'r-caret=6.0*' \
    'r-rcurl=1.95*' \
    'r-crayon=1.3*' \
    'r-randomforest=4.6*' \
    'r-htmltools=0.3*' \
    'r-sparklyr=0.7*' \
    'r-htmlwidgets=1.0*' \
    'r-hexbin=1.27*'

RUN conda install --quiet --yes 'r-rjava' && \
    conda clean -tipsy && \
    fix-permissions $CONDA_DIR

# Switch back to jovyan to avoid accidental container runs as root
USER $NB_UID
COPY config/Rprofile $HOME/.Rprofile
COPY config/R_parse_odbc.py $HOME/R_parse_odbc.py
RUN R CMD javareconf && \
    R -e 'install.packages("DBI")' && \
    R -e 'install.packages("odbc")'
