FROM alpine:3.8

ENV \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    CONDA_DIR=/opt/conda

ENV \
    PATH="$CONDA_DIR/bin:$PATH"

RUN \
    apk add --no-cache --virtual .build-deps \
        bash=4.4.19-r1 \
        build-base=0.5-r1 \
        git=2.18.1-r0 \
        wget=1.19.5-r0 && \
    wget https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub -O /etc/apk/keys/sgerrand.rsa.pub && \
    echo "8d6f142f06af51fa5533245d48f2248f  /etc/apk/keys/sgerrand.rsa.pub" | md5sum -c && \
    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-2.28-r0.apk && \
    echo "e1107610a518b879adeb39a2d4b2385e  glibc-2.28-r0.apk" | md5sum -c && \
    apk add --no-cache \
        glibc-2.28-r0.apk && \
    rm /etc/apk/keys/sgerrand.rsa.pub && \
    rm glibc-2.28-r0.apk && \
    wget http://repo.continuum.io/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh -O miniconda.sh && \
    echo "e1045ee415162f944b6aebfe560b8fee  miniconda.sh" | md5sum -c && \
    mkdir -p "$CONDA_DIR" && \
    bash miniconda.sh -f -b -p "$CONDA_DIR" && \
    rm miniconda.sh && \
    conda config --system --prepend channels conda-forge && \
    conda config --system --set auto_update_conda false && \
    conda config --system --set show_channel_urls true && \
    conda install --yes \
        'basemap=1.2.0' \
        'bokeh=0.13.0' \
        'dask=0.19.3' \
        'font-ttf-dejavu-sans-mono==2.37' \
        'gensim=3.5.0' \
        'ipython-sql=0.3.9' \
        'ipython=6.5.0' \
        'jupyterhub=0.9.2' \
        'jupyterlab=0.34.12' \
        'keras=2.2.4' \
        'matplotlib=3.0.0' \
        'networkx=2.2' \
        'nltk=3.3.0' \
        'notebook=5.7.0' \
        'numpy=1.15.2' \
        'openssl=1.0.2p' \
        'pandas=0.23.4' \
        'psycopg2=2.7.5' \
        'pyldavis=2.1.2' \
        'pytorch=0.4.1' \
        'r-base=3.4.1' \
        'r-cairo=1.5_9' \
        'r-caret=6.0_80' \
        'r-dbi=1.0.0' \
        'r-forecast=8.2' \
        'r-irkernel=0.8.12' \
        'r-plyr=1.8.4' \
        'r-reshape2=1.4.3' \
        'r-rpostgres=1.1.1' \
        'r-tidyverse=1.2.1' \
        'scikit-learn=0.20.0' \
        'scipy=1.1.0' \
        'seaborn=0.9.0' \
        'spacy=2.0.12' \
        'tensorboard=1.10.0' \
        'tensorflow=1.10.0' \
        'theano=1.0.3' \
        'tini=0.18.0' \
        'toolz=0.9.0' \
        'xgboost=0.80' \
        'xorg-libxext=1.3.3' \
        'xorg-libxrender=0.9.10' && \
    conda clean -tipsy && \
    pip install \
        pip==18.1 && \
    pip install \
        jupyters3==0.0.29 \
        pattern3==3.0.0 \
        -e git+git://github.com/aboSamoor/polyglot@d0d2aa8d06cec4e03bd96618ae960030f7069a17#egg=polyglot && \
    apk del .build-deps

COPY jupyterlab_database_access /jupyterlab_database_access
RUN \
    jupyter labextension install \
        @jupyterlab/hub-extension@^0.11.0 \
        /jupyterlab_database_access && \
    npm cache clean --force && \
    node /opt/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js cache clean

COPY config/jupyter_notebook_config.py /etc/jupyter/jupyter_notebook_config.py
COPY config/async_http_logging_handler.py /opt/conda/lib/python3.6/site-packages/

ENTRYPOINT ["tini", "-g", "--"]

RUN adduser -S jovyan
USER jovyan
