FROM jupyter/base-notebook:137a295ff71b

USER root

RUN pip install --upgrade \
    pip==18.0 \
    s3contents==0.1.10 \
    dask==0.19.2 \
    toolz==0.9.0 \
    nose==1.3.7 \
    s3fs==0.1.6 \
    gcsfs==0.1.2 \
    dj-database-url==0.5.0 \
    psycopg2-binary==2.7.5 \
    ipython-sql==0.3.9

RUN conda config --system --prepend channels conda-forge && \
    conda config --system --set auto_update_conda false && \
    conda config --system --set show_channel_urls true && \
    conda install --quiet --yes \
    notebook \
    'r-base=3.4.1' \
    'r-irkernel=0.8*' \
    'r-plyr=1.8*' \
    'r-devtools=1.13*' \
    'r-tidyverse=1.1*' \
    'r-shiny=1.0*' \
    'r-rmarkdown=1.8*' \
    'r-forecast=8.2*' \
    'r-rsqlite=2.0*' \
    'r-reshape2=1.4*' \
    'r-nycflights13=0.2*' \
    'r-caret=6.0*' \
    'r-rcurl=1.95*' \
    'r-crayon=1.3*' \
    'r-randomforest=4.6*' \
    'r-htmltools=0.3*' \
    'r-sparklyr=0.7*' \
    'r-htmlwidgets=1.0*' \
    'r-hexbin=1.27*' \
    'r-rjava' && \
    conda clean -tipsy && \
    npm cache clean --force && \
    fix-permissions $CONDA_DIR

COPY config/Rprofile $HOME/.Rprofile
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-utils && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends fonts-dejavu gfortran build-essential libpq-dev unixodbc-dev odbc-postgresql && \
    R -e 'install.packages("DBI")' && \
    R -e 'install.packages("odbc")' && \
    apt-get remove -y gfortran build-essential apt-utils && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY config/jupyter_notebook_config.py /etc/jupyter/jupyter_notebook_config.py

# Switch back to jovyan to avoid accidental container runs as root
USER $NB_UID
